#!/bin/bash

# Target directory
TARGET_DIR="/opt/Airlinq/ansible/amx_ansible/group_vars"

# List of hostnames
HOSTS=(
"DLVMTMAMXOPS01"
"DLVMAMXHMST01"
"DLVMAMXHNN01"
"DLVMAMXHNN02"
"DLVMAMXHNN03"
"DLVMAMXGCLB01"
"DLVMAMXOMBSSDB02"
"DLVMMAXBRBSSDB01"
"DLVMMAXALLBSSDB03"
"DLVMAMXOLDB01"
"DLVMAMXOLDB02"
"DLVMAMXOLDB03"
"DLVMAMXMEDIADB01"
"DLVMAMXMASTERDB01"
"DLVMAMXREPLICA01"
"DLVMAMXSECONDARYDB01"
"DLVMAMXREPLICA02"
"DLVMAMXRECDRDB02"
"DLVMAMXRECDRDB03"
"DLVMAMXPRODGCDBREP02"
"DLVMANSIBLECONTR01"
"DLVMAMXSFTP01"
"DLVMAMXACONTOL01"
"DLVMAMXAPI02"
"DLVMAMXNBAPI01"
"DLVMAMXNBAPI02"
"DLVMAMXGOUPSB01"
"DLVMAMXOCS01"
"DLVMAMXOCSDRA1"
"DLVMAMXNC01"
"DLVMAMXMXBSS01"
"DLVMAMXBRBSS01"
"DLVMAMXGCCDR01"
"DLVMAMXMEDIAAPP01"
"DLVMAMXBILLING02"
"DLVMAMXDSMXOCS01"
"DLVMAMXDSBROCS01"
"DLVMAMXORA03"
"DLVMAMXORA04"
"DLVMAMXACONTOL02"
"DLVMAMXETL01"
"DLVMAMXSMSC01"
	)

# Create target directory if it doesn't exist
mkdir -p "$TARGET_DIR"

# Create .yml files for each host
for HOST in "${HOSTS[@]}"; do
  FILE="${TARGET_DIR}/${HOST}.yml"
  if [[ ! -f "$FILE" ]]; then
    cat <<EOF > "$FILE"
# Variables for $HOST
---
# Add host-specific variables below
EOF
    echo "Created: $FILE"
  else
    echo "Skipped (already exists): $FILE"
  fi
done

